# Use Auto DevOps pipeline
# https://gitlab.com/gitlab-org/gitlab/blob/master/lib/gitlab/ci/templates/Auto-DevOps.gitlab-ci.yml
include:
- template: Auto-DevOps.gitlab-ci.yml

variables:
  # application variables
  K8S_SECRET_NEXT_PUBLIC_SUPABASE_URL: http://production-supabase-kong.supabase-production.svc.cluster.local:8000
  K8S_SECRET_NEXT_PUBLIC_SUPABASE_ANON_KEY: $SUPABASE_ANON_KEY

  # disable auto devops tests
  BROWSER_PERFORMANCE_DISABLED: 1
  CODE_INTELLIGENCE_DISABLED: 1
  CODE_QUALITY_DISABLED: 1
  CONTAINER_SCANNING_DISABLED: 1
  DAST_DISABLED: 1
  DEPENDENCY_SCANNING_DISABLED: 1
  SAST_DISABLED: 1
  LICENSE_MANAGEMENT_DISABLED: 1
  LOAD_PERFORMANCE_DISABLED: 1
  PERFORMANCE_DISABLED: 1
  SECRET_DETECTION_DISABLED: 1
  TEST_DISABLED: 1

  # configure auto devops components
  REVIEW_DISABLED: 1
  AUTO_DEVOPS_BUILD_IMAGE_EXTRA_ARGS: >-
    --build-arg NEXT_PUBLIC_SUPABASE_URL=$K8S_SECRET_NEXT_PUBLIC_SUPABASE_URL
    --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=$K8S_SECRET_NEXT_PUBLIC_SUPABASE_ANON_KEY

  # Agent
  KUBE_INGRESS_BASE_DOMAIN: kubedev.scholarsportal.info
  KUBE_CONTEXT: ai-ml/gitlab-agent:kubedev
  KUBE_NAMESPACE: $CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG # or $CI_ENVIRONMENT_SLUG
