services:
  portal:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      NEXT_PUBLIC_SUPABASE_URL:
      NEXT_PUBLIC_SUPABASE_ANON_KEY:
    network_mode: host
